/*!
 * \file      Commissioning.h
 *
 * \brief     End device commissioning parameters
 *
 * \copyright Revised BSD License, see section \ref LICENSE.
 *
 * \code
 *                ______                              _
 *               / _____)             _              | |
 *              ( (____  _____ ____ _| |_ _____  ____| |__
 *               \____ \| ___ |    (_   _) ___ |/ ___)  _ \
 *               _____) ) ____| | | || |_| ____( (___| | | |
 *              (______/|_____)_|_|_| \__)_____)\____)_| |_|
 *              (C)2013-2017 Semtech
 *
 * \endcode
 *
 * \author    Miguel Luis ( Semtech )
 *
 * \author    Gregory Cristian ( Semtech )
 *
 * \author    Marten Lootsma(TWTG) on behalf of Microchip/Atmel (c)2017
 */
#ifndef __LORA_COMMISSIONING_H__
#define __LORA_COMMISSIONING_H__

/*!
 ******************************************************************************
 ********************************** WARNING ***********************************
 ******************************************************************************
  The crypto-element implementation supports both 1.0.x and 1.1.x LoRaWAN 
  versions of the specification.
  Thus it has been decided to use the 1.1.x keys and EUI name definitions.
  The below table shows the names equivalence between versions:
               +-------------------+-------------------------+
               |       1.0.x       |          1.1.x          |
               +===================+=========================+
               | LORAWAN_DEVICE_EUI| LORAWAN_DEVICE_EUI      |
               +-------------------+-------------------------+
               | LORAWAN_APP_EUI   | LORAWAN_JOIN_EUI        |
               +-------------------+-------------------------+
               | N/A               | LORAWAN_APP_KEY         |
               +-------------------+-------------------------+
               | LORAWAN_APP_KEY   | LORAWAN_NWK_KEY         |
               +-------------------+-------------------------+
               | LORAWAN_NWK_S_KEY | LORAWAN_F_NWK_S_INT_KEY |
               +-------------------+-------------------------+
               | LORAWAN_NWK_S_KEY | LORAWAN_S_NWK_S_INT_KEY |
               +-------------------+-------------------------+
               | LORAWAN_NWK_S_KEY | LORAWAN_NWK_S_ENC_KEY   |
               +-------------------+-------------------------+
               | LORAWAN_APP_S_KEY | LORAWAN_APP_S_KEY       |
               +-------------------+-------------------------+
 ******************************************************************************
 ******************************************************************************
 ******************************************************************************
 */

/*!
 * When set to 1 the application uses the Over-the-Air activation procedure
 * When set to 0 the application uses the Personalization activation procedure
 */
#define OVER_THE_AIR_ACTIVATION                            0

/*!
 * When using ABP activation the MAC layer must know in advance to which server
 * version it will be connected.
 */
#define ABP_ACTIVATION_LRWAN_VERSION_V10x                  0x01000300 // 1.0.3.0

#define ABP_ACTIVATION_LRWAN_VERSION                       ABP_ACTIVATION_LRWAN_VERSION_V10x

/*!
 * Indicates if the end-device is to be connected to a private or public network
 */
#define LORAWAN_PUBLIC_NETWORK                             true

/*!
 * IEEE Organizationally Unique Identifier ( OUI ) (big endian)
 * \remark This is unique to a company or organization
 */
#define IEEE_OUI                                           0x00, 0x00, 0x00

/*!
 * Mote device IEEE EUI (big endian)
 *
 * \remark In this application the value is automatically generated by calling
 *         BoardGetUniqueId function
 */
#define LORAWAN_DEVICE_EUI                                 { 0x00, 0x94, 0x72, 0x61, 0x08, 0x57, 0xC0, 0xBC } // for ABP
//#define LORAWAN_DEVICE_EUI                                 { 0x00, 0xB3, 0x84, 0xE1, 0xE7, 0x62, 0xEE, 0xB5 }	// for OTAA
															 //0xAA, 0xBB, 0xCC, 0xDD, 0xEE, 0xFF, 0x77, 0x78 }
//															 0x00, 0x94, 0x72, 0x61, 0x08, 0x57, 0xC0, 0xBC }

/*!
 * App/Join server IEEE EUI (big endian)
 */
//#define LORAWAN_JOIN_EUI                                   { 0x70, 0xB3, 0xD5, 0x7E, 0xD0, 0x00, 0xF8, 0x06 }
//#define LORAWAN_JOIN_EUI                                   { 0x70, 0xB3, 0xD5, 0x7E, 0xD0, 0x01, 0x5B, 0x5E }
#define LORAWAN_JOIN_EUI                                   { 0x70, 0xB3, 0xD5, 0x7E, 0xD0, 0x01, 0x5B, 0x5E }

/*!
 * Application root key
 * WARNING: NOT USED FOR 1.0.x DEVICES
 */
//#define LORAWAN_APP_KEY                                    { 0x6E, 0x66, 0x95, 0x18, 0xD1, 0x7E, 0x15, 0x4C, 0x50, 0x46, 0x4A, 0xF8, 0x0B, 0x4A, 0xA1, 0x31 }
//#define LORAWAN_APP_KEY                                    { 0x54, 0xFC, 0x61, 0x99, 0x21, 0x01, 0x95, 0xE0, 0x47, 0xC3, 0xE5, 0xB4, 0x54, 0xBB, 0x52, 0x3E }
#define LORAWAN_APP_KEY                                    { 0x2C, 0xAA, 0xCC, 0x99, 0x9B, 0x53, 0x1C, 0x16, 0x2D, 0x30, 0x93, 0x8A, 0x15, 0xD6, 0xD6, 0x5B }

/*!
 * Network root key
 * WARNING: FOR 1.0.x DEVICES IT IS THE \ref LORAWAN_APP_KEY
 */
//#define LORAWAN_NWK_KEY                                    { 0x6E, 0x66, 0x95, 0x18, 0xD1, 0x7E, 0x15, 0x4C, 0x50, 0x46, 0x4A, 0xF8, 0x0B, 0x4A, 0xA1, 0x31 }
#define LORAWAN_NWK_KEY                                    { 0x54, 0xFC, 0x61, 0x99, 0x21, 0x01, 0x95, 0xE0, 0x47, 0xC3, 0xE5, 0xB4, 0x54, 0xBB, 0x52, 0x3E } // for ABP
//#define LORAWAN_NWK_KEY                                    { 0x2C, 0xAA, 0xCC, 0x99, 0x9B, 0x53, 0x1C, 0x16, 0x2D, 0x30, 0x93, 0x8A, 0x15, 0xD6, 0xD6, 0x5B } // for OTAA
/*!
 * Current network ID
 */
#define LORAWAN_NETWORK_ID                                 ( uint32_t )0

/*!
 * Device address on the network (big endian)
 *
 * \remark In this application the value is automatically generated using
 *         a pseudo random generator seeded with a value derived from
 *         BoardUniqueId value if LORAWAN_DEVICE_ADDRESS is set to 0
 */
#define LORAWAN_DEVICE_ADDRESS                             ( uint32_t )0x26011BE6
//260128FF
//0x26011BE6

/*!
 * Forwarding Network session integrity key
 * WARNING: NWK_S_KEY FOR 1.0.x DEVICES
 */
//#define LORAWAN_F_NWK_S_INT_KEY                            { 0x64, 0xD3, 0x88, 0x62, 0xC0, 0x01, 0x77, 0x28, 0x59, 0x88, 0x56, 0x18, 0x88, 0x6A, 0xCB, 0x19 }
#define LORAWAN_F_NWK_S_INT_KEY                            {  0xFE, 0x83, 0xC1, 0x72, 0x8B, 0x61, 0x36, 0x3F, 0x17, 0x91, 0x9D, 0x95, 0x11, 0x4D, 0x2C, 0x0A }

/*!
 * Serving Network session integrity key
 * WARNING: NOT USED FOR 1.0.x DEVICES. MUST BE THE SAME AS \ref LORAWAN_F_NWK_S_INT_KEY
 */
//#define LORAWAN_S_NWK_S_INT_KEY                            { 0x64, 0xD3, 0x88, 0x62, 0xC0, 0x01, 0x77, 0x28, 0x59, 0x88, 0x56, 0x18, 0x88, 0x6A, 0xCB, 0x19 }
#define LORAWAN_S_NWK_S_INT_KEY                            { 0xFE, 0x83, 0xC1, 0x72, 0x8B, 0x61, 0x36, 0x3F, 0x17, 0x91, 0x9D, 0x95, 0x11, 0x4D, 0x2C, 0x0A }

/*!
 * Network session encryption key
 * WARNING: NOT USED FOR 1.0.x DEVICES. MUST BE THE SAME AS \ref LORAWAN_F_NWK_S_INT_KEY
 */
//#define LORAWAN_NWK_S_ENC_KEY                              { 0x64, 0xD3, 0x88, 0x62, 0xC0, 0x01, 0x77, 0x28, 0x59, 0x88, 0x56, 0x18, 0x88, 0x6A, 0xCB, 0x19 }
#define LORAWAN_NWK_S_ENC_KEY                              { 0xFE, 0x83, 0xC1, 0x72, 0x8B, 0x61, 0x36, 0x3F, 0x17, 0x91, 0x9D, 0x95, 0x11, 0x4D, 0x2C, 0x0A }

/*!
 * Application session key
 */
//#define LORAWAN_APP_S_KEY                                  { 0x11, 0xDC, 0x1B, 0x30, 0x07, 0xA1, 0xE5, 0xF9, 0xB7, 0x6A, 0xC6, 0xC6, 0xDD, 0xF3, 0x4C, 0x7B }
#define LORAWAN_APP_S_KEY                                  {  0x54, 0xFC, 0x61, 0x99, 0x21, 0x01, 0x95, 0xE0, 0x47, 0xC3, 0xE5, 0xB4, 0x54, 0xBB, 0x52, 0x3E }

#endif // __LORA_COMMISSIONING_H__
